runtime: python27
threadsafe: true

handlers:
- url: /questions
  script: server.main.app

- url: /
  static_files: client/index.html
  upload: client/index.html

- url: /js
  static_dir: client/js

- url: /partials
  static_dir: client/partials
